---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mosquitto-passwd
  namespace: mosquitto
spec:
  encryptedData:
    passwd: AgC7D+lgPhBC2Az1XShVjrjuthBibyTTqVKmJgpmAZiJbl21NKCq6Ubyx5BMJwnYhY/C9cI2wBH6Tw/cnp43C3kFek3sSoHOeyCWpwFljWflO3fakic601QYoi9DzTdofKnA89zg63NZZRhQTOjYPOkUxo9BNHJv9G1Wqosk2/IwE/2MNDrJv/J43N5ncSnZUr10y4zEL5lf9PyaQMJzk5pTt4B6jjs3stDiw9YhDMCdRkEG94+wzpezXqw/1MNE/JkMQpVktNoduJeB1hKqoqPfzzgyfbt3abuUm3kbwmu1qGcxPEDmiveIJCRdFJFEVCz7Vko4Pc/mUcm1uyVdoRd3oSGHDkhUIRDT7QY/vyETmkcPNQTbmSoRxcrDDMENN+3xuWYQuT/kUKSrGWjhnNrmmxKEogwzRVx1t0CyhbcmWPWcdxeK7Zs+jQwy/emrhM2wsRDfGPJ6mTR+CHPvMnCODRNBFNjSyBvn/pF43V6TAi4XL7kHE7KYcHMwZKxQcIpdu35w4atF0N0JXOqjnjwbK+EYl1aPI7+yxiyIPriezeWzlYsQqAy2fqvXY6zh6QungOhcmw7WhKlPqG4kj8T8k8DGQ4v9z8tBAgI8gSmGDOUM+gI9ijb6BFZ2U2cNNhLUcFljzdMM5Uo/r49BiWkXE3Ll0Tt6zOyyi6eRmvQm6ihTjxo7cZekqjDWh587Mv7yBreMkqjOaNN4YV5CG2MyxAgNSASZjEwBb68wPioIdRoP3/rMG/POyYPWlL/nSONuG8jWfg3iqjJ9eP+J8MHFBO9BZh69aMmh42Vh1Ed7QUFgTayNE4DpRUVcRcKp4kQdDzTt6v4izg1Y5gEVD/2ZB0JVntyRY5pyWY2VQEUVkI5aecbt+9PfmsLPxE81Vt7LyKFLzcsEqjkprLDZFJFRh5LYYd6QXBSA1lRlYmsqKgFNX196Zhjyx9UitkFgVg==
  template:
    metadata:
      name: mosquitto-passwd
      namespace: mosquitto
