---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-encryption-key
  namespace: homarr
spec:
  encryptedData:
    encryption-key: AgBTs+vhi7bo6W8p2cVSvZ21HoRciQeEsqK3OCGzI/yMVhK8Y5UQlGZx4/eEyRtJU1gQGateNAtsZfpYXMxj4rBqF1Ur21C03K6z4ykzoqF683ICDjIJMqylMHO1pVkddfwN61o4TSkHBzqZ8vhdb6nOnjKxbK8938GsoODF7N1NEXSTIim3Y8Br7weUuS6qt9ZpJtXoaQtNOEDrwJqqLqyZkCeCuRXfAcD7X6vwb9it2DhRrQMRTnzz4A89djHsNiYWYyOTmaFY3aCO/p26xr92tRuPY6zfGgIkbTmfGXQJ53mTAw/xUX0PEbmqfOMiIwwqKjJiwzernaGx+zc5BmgqZxcye23jJX4133u9bm9hkGrcKH7Cfh8fjv02eVwk+yn/P6bii//YgwvDv/d96C5Imk8l+kr9cgHKzPTvBrTtUzje6WTXbQB7HDopsUbbhUt03tw9oLq9o8fwQYDs2VvhgUFAb1nzHDQ/zyCuEFOxiw7LVTcQpeL5iTu8BOu5gx5cMLpnwj0du/PSkaSK9fqFJ9S+YXLyotuPiKr5AnLK+93h6MeJ8J05pu618JWuiNRVWueXE5RztJJVCH12CrrfbrVsJcdMQMhtscAfORkkZzT4IM3+BFVESAa8fhE5ocVLBMY1a6UgmcUgsWc7AJwu0Dz+8zrfazqATmXgcUdQEJXAKm4GF2DGKm85qSNeW4oALLcQustuygrzp+l1MLkpW/zbsyTAILm5RliU2HuhpP8ALXqyaRL3oqyCqpVX2xjNvl/ivvcWffdioWfyidHt
  template:
    metadata:
      name: homarr-encryption-key
      namespace: homarr
