apiVersion: v1
kind: Service
metadata:
  name: adguard
spec:
  type: LoadBalancer
  selector:
    app: adguard
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dhcp-udp
      port: 67
      targetPort: 67
      protocol: UDP
    - name: dhcp-client-udp
      port: 68
      targetPort: 68
      protocol: UDP
    - name: setup
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: dot-tcp
      port: 853
      targetPort: 853
      protocol: TCP
    - name: dot-udp
      port: 853
      targetPort: 853
      protocol: UDP
    - name: doq
      port: 784
      targetPort: 784
      protocol: UDP
    - name: doq-alt
      port: 8853
      targetPort: 8853
      protocol: UDP
    - name: doh3-tcp
      port: 5443
      targetPort: 5443
      protocol: TCP
    - name: doh3-udp
      port: 5443
      targetPort: 5443
      protocol: UDP
