---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials
  namespace: mariadb
spec:
  encryptedData:
    grimmory_pass: AgAQP8/M55u6k7r0GcVWXTOus9ppyC8Cbd/2oPO2fx++j6FpyV2rvf3cFuDJCaP33P4QQ9HN1FtkgQCUHE9hrJGdyWYWwopJmGU5vqEiS47DFXzrgKnYMPdlfx72TFHNWvKzzm84rSJp+iwlya3fWn/MmrIedhvV6n13vJcFymXq2NwPiylROsxISJ3s/1riI57Zmhsyo8ChU/DIuIvNnfq6yRvpCPuvo2sxrTTVh7Lzuhv5uvgOYhIIwz1x2df6F+dc8nS4CfY6rAIj7vTaq0l6pJKiEPfEL/j38aFuDL95pgSEYwOrnCA9i+nsQzcnkfsXRapKH9GUrkBkZtmid5bmVnzAY313aXortKonATV2/fhmcUeRT2JsJiZT7r/n/fzCznjJ4ZUl6cX0aIbXAh93SntYmHx1/SsORb6C1POPPy0UXf7vzbUNMUzBveSuFYrZ/QVk9o0nXIrVJOa+HozDsOEqI/Ks5PMtvlll5HHGQ3h2OKScJ2dc4EIpYbqt9+c5gFAUh6w5dXqKgC1dLkGLgALAjLacFFNLdWHoRyyfAEGOXveFeTWtpXyLQJLfdkiN2+FsIOw6aXvAacfz8FTPhePgqP/33gDt1w1CNb4dNJ4C96ayf9jYf1UTce/PteDMESPOwDB9c2Wkqse2RKNXLvpKH4l6ywnKGFm5lMuGBsqTWOYiky0z72hq/JQEIQeDi/BpxQAu0dts3TCPKQwZLlE=
    mariadb_pass: AgCkZX2cL4p3XQZCm4A748nKH86v3tqpW2tWHDXhgf75eD4pJNGRypUDWtm3DMQK0gE+f3pt2GyOGmQI74f1BlMXmQjaNvxEPYdJhqYOvxTiiVRFyBfln9P9I0x3buQI841uQfMbOOEnSLSIoFq5JlRPHqngKzBMXDC3leQAhct/3YbPWMjWuj16ZbkL/DZKXwgreZV2FrZAjr+t/8tnBiEA24i5QkHBrrM5mit8j15VmOCG8UmDULRdPm4M/j26sngHN+8pbiL0eWfWnGF1bxtmM5LJACymWJeIJuiXR9uXVMOTrrHnIz+lY74gEBtSLqW7gu9B4QbBHxZsQURnTASeDS/CUAuUOwTUCTSdy8I9xhZ4oTHHzhonP4XmGm03u8pL/kF3++JabOVYvMq7mClE0i1nkbvXQiPWwGdy0r/vXw5rQI8Vpduxrv7MIjhR8jm4uvUSqVzNs9nvjFO7vD4Zysnz9YTNteMScYkDINhvAUFkvjVwAaeyYOIB9D3wmPNUfh4qZj7tB9JBVYi5gCA4PX2auuA+LWa59VvzvJ4k86TbBEJMwd/iUNIxsSQXiDYjJTLKH46X4X3N3Nsz/nJ0RpuZgni1sfjVseXNfGb9krGempAr0FEo30Fbjh6jUw3Lg6/JR0+wySlsF9RNTGZVnDOeu5B2/nA9FLsHS+P6KacfHkYMfC4uarzun0Cfumg1C4QS9ohY9AZ2IuxfAvs/AJU=
  template:
    metadata:
      name: mariadb-credentials
      namespace: mariadb
