apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  revisionHistoryLimit: 0 
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
        - name: movies
          hostPath: 
            path: /srv/mergerfs/mergefs/data/media/movies
        - name: tvshows
          hostPath: 
            path: /srv/mergerfs/mergefs/data/media/tv
        - name: config
          hostPath:
            path: /srv/dev-disk-by-uuid-f0d9ee2e-5550-4e41-897d-9b8d2d01c681/pod_config/jellyfin         
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:10.11.8
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Warsaw"
            - name: JELLYFIN_CACHE_DIR
              value: "/config/cache"
            - name: JELLYFIN_TRANSCODES_DIR
              value: "/config/data/transcodes"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data/movies
              name: movies
            - mountPath: /data/tvshows
              name: tvshows
          ports:
              - containerPort: 8096
