apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgress
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/czerus/yoda-gitops
    targetRevision: HEAD
    path: postgress

  destination:
    server: https://kubernetes.default.svc
    namespace: postgress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true