config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/czerus/yoda-gitops
      targetRevision: master

applications:
  - name: jellyfin
    tool:
      helm:
        releaseName: jellyfin
