---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grimmory-credentials
  namespace: grimmory
spec:
  encryptedData:
    grimmory_pass: AgCeroJ3t3or6LjNL98IgdM2Hnc8Owh+nNmTfWB2n5SpsMDWBhICBV3nQ71xGCKFVSOrnClw8zoNCUh8CJEwlUFmmI7qKAFuGIE2v6O6LEm0S3zf+hGkyL3dMXy3PJREeEI3dJpeWUdDvqjOpOH5DpPsW1u3Dq02cyoKwEOmGOIeNUpIw2LeTzMaKinVHYSJUN+xBuzeH9VTjXTJGVUV0/plhSoSjOeNdQS0hOcOfPLMmgvrePqzsZkS6C0pRAaj3vKxrhCsuszyjbSrxUKy/4CGl7Ljq7+df6GKtDydEHgNpofSZviCtt0EDFlkGMax9kOpsywrw80VvEvS1sqHlnGcfrFz/1svRtS7Z9wXMJzwchpf3wyLuLZqiGQWBZhZ9gkYV7lpoZIcAn5DgUsiFUXMJoInWsIgbwoGlxUvABQ9520a9aXW6Q8nTcSTg1Wu/ieL2YTu2XN3/OdZ60F6IE+kD9WCxAlwt7j17UXDgqzDZktnf9rzs9FGqbEstwVNSG4FLGp12Jr9+26Zovp6+nui2IYqciIOZLyq5M6Pdn83VdLTB/vJHmC4NFr3dJOcXvZS5pGVohwtxXM6Z61VQUh4O/jZhWX00QwpZI1VvikZjXcvckxeM5VS84qp0lJosji/bSeTCgh6ifAhVmC9YKjVUIdqU0fJ+ynt/L/CEjcsdAF9MTz8OBn1/5Om7Ht4fZovuofHY4iOVhfxlqHo2I3VrgQ=
  template:
    metadata:
      name: grimmory-credentials
      namespace: grimmory
